# Generated by Django 4.0.5 on 2022-06-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
