# Generated by Django 4.0.5 on 2022-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0002_alter_studentmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
