# Generated by Django 4.0.5 on 2022-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0003_alter_studentmodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
