# Generated by Django 4.0.5 on 2022-06-20 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0004_alter_studentmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayeFeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_amt', models.FloatField()),
                ('description', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeapp.studentmodel')),
            ],
        ),
    ]
