# Generated by Django 4.0.5 on 2022-06-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0005_payefeesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
