# Generated by Django 4.0.5 on 2022-06-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0007_payefeesmodel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
