# Generated by Django 4.0.5 on 2022-06-23 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0008_alter_studentmodel_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTopicModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=500)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeapp.coursemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTasksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sample_input', models.TextField(null=True)),
                ('sample_output', models.TextField(null=True)),
                ('topics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officeapp.coursetopicmodels')),
            ],
        ),
    ]
