# Generated by Django 4.0.5 on 2022-06-23 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0009_coursetopicmodels_coursetasksmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursetasksmodel',
            old_name='title',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='coursetopicmodels',
            old_name='topics',
            new_name='topic',
        ),
    ]
